### ISSUE TITLE
Test suite dependencies

### ISSUE THREAD

**Issue by nomeata** [ddssff/cabal-debian#10]
For packages having a test suite (and unless a `--not-testsuite` flag has been passed), it should add
```
DEB_ENABLE_TESTS = yes
```
and also add the dependencies of the test suite. For these, no `-prof` and `-doc` packages should be dependent upon, and libraries already dependent upon by the main library should not be repeated. I guess this requires a little bit of coding.

**Comment by ddssff** [comment]
How does this relate to

    DEB_BUILD_OPTIONS = nocheck

That appears to cause the --enable-tests flag to be omitted from the configure_recipe.

**Comment by ddssff** [comment]
Ok, this is working well now.

**Comment by ddssff** [comment]
Ok, now I have all these options turned around.  Working on it...

**Comment by ddssff** [comment]
Hmm, for some reason the testEnabled flag in the PackageDescription returned by finalizePackageDescription (in Distribution.PackageDescription.Configuration is always set to False.

**Comment by nomeata** [comment]
I had a look; looks good so far. But there is a possible improvement: For the test suite, we do not need the `-prof` and the `-doc` packages, so dependencies that are only there due to the test suite should only be listed in their `-dev` variant.
