### ISSUE TITLE
Install data-files into /usr/share/PackageName/?

### ISSUE THREAD

**Issue by ddssff** [ddssff/cabal-debian#28]
Currently the data-files are installed into "/usr/share" </> map toLower packagename, but I'm pretty sure this is wrong (for packages that have capital letters in their names.)  Also, it was ignoring the value returned by Distribution.PackageDescription.dataDir, but I think it needs to prefer this to the constructed value.

**Comment by ddssff** [comment]
Hmm, the only hackage package I see with data-dir set to a non-empty string are js-flot and js-jquery, which set them to just "javascript".

**Comment by nomeata** [comment]
haskell-devscripts passes `--datasubdir=$(CABAL_PACKAGE)`. Why do you think it is wrong?

**Comment by ddssff** [comment]
So far I've been confusing where to find them in the source tree with where to put them in the installed binary package tree.

**Comment by ddssff** [comment]
I think I just need to stop lowercasing $(CABAL_PACKAGE) in Debian/Debianize/Input.hs

**Comment by nomeata** [comment]
Not really. The variable CABAL_PACKAGE is used for the foo in libghc-foo-dev (maybe a badly named variable, but it’s grown code...), so lower-casing this is correct.

Why do you have to know about the data directory at all? Doesn’t haskell-devscripts take care of that?

**Comment by ddssff** [comment]
Cabal-debian builds the debian/*.install files, which contain the files listed in the data-files field of the cabal file.  It also adds files to the install files for other reasons.

**Comment by ddssff** [comment]
Oh, I wasn't going to leave it upper case for package names, just for the directory containing the installed data files.

**Comment by nomeata** [comment]
Right, but I’m confused (independent of whether its a good idea or not) about why this is a `cabal-debian` bug, and not one against haskell-devscripts.

**Comment by ddssff** [comment]
This is confusing and I think it is resolved.  So I'll close it.
