### ISSUE TITLE
Build Failures

### ISSUE THREAD

**Issue by creichert** [ddssff/cabal-debian#31]
I enabled travis on my local machine and noticed build failures on GHC 7.6 & 7.8: https://travis-ci.org/creichert/cabal-debian/jobs/49557165#L625

I can fix the issue but did not want to start spraying CPP everywhere so I'll need a bit more time.

Is anyone opposed to using travis? It could be really helpful migrating to 7.10 and for pull requests.

See my travis file: https://github.com/creichert/cabal-debian/blob/master/.travis.yml

**Comment by ddssff** [comment]
I think travis is a great thing, I just haven't learned how to use it.  All contributions welcome!

I'm also a lonely supporter of CPP - I was going to post something about it, I like it because its *not* Haskell - if you squint at your program the right way you see one beautiful Haskell program that only works with the latest libraries, along side another uglier one that works with the old stuff.

**Comment by ddssff** [comment]
AbiTag appeared in Cabal 1.22

**Comment by ddssff** [comment]
Not quite.

**Comment by ddssff** [comment]
I have a lot of messed up build dependency issues I have to resolve.  I'm off to add travis files to a bunch of repositories.

**Comment by creichert** [comment]
Not a problem, I've found that travis build file really helpful as well. Are you primarily installing dependencies from apt or hackage?

**Comment by ddssff** [comment]
Primarily from hackage.  I have a puzzling situation here:  https://travis-ci.org/seereason/cabal-debian

That is a throwaway fork.  It seems as if it is getting errors from code marked #if !MIN_VERSION_Cabal(1,22,0) when building the Cabal-1.22 version.

**Comment by ddssff** [comment]
I'm not convinced that travis-ci.org is able to build using Cabal-1.22.  I'm getting 1.18.1 no matter what I do.

**Comment by creichert** [comment]
Are you referencing this line: https://travis-ci.org/seereason/cabal-debian/jobs/49861499#L94

I think travis is using the correct version but spitting out 1.18.1 initially.
https://travis-ci.org/seereason/cabal-debian/jobs/49861498#L330


Similarly, another project of mine has misleading output initially but is using the correct version:
https://travis-ci.org/creichert/bencode/jobs/48067300#L387


I can look at this a bit more today and try to get it fully working on my fork, first.

**Comment by creichert** [comment]
It looks like travis echos all it's information before the scripts have time to set up cabal and ghc:

I think we are getting the right versions in there but I could be wrong:
https://travis-ci.org/seereason/cabal-debian/jobs/49861499#L288

**Comment by ddssff** [comment]
I found that I had to make updates to the Unixutils and debian packages to get cabal-debian to build - are you using these new versions?  I have done some work on the cabal-debian ifdefs, let me know if you want to complete yours or if I should finish mine.

**Comment by ddssff** [comment]
The current repo successfully builds on ghc-7.6 and 7.8 and with Cabal-1.18 thru 1.22.  I guess its not too surpising that a package with cabal in its name would have a lot of Cabal ifdefs.  I'm happy to accept fixes for 7.10 and beyond!

**Comment by creichert** [comment]
I must have missed the notifications. Thanks a lot! I agree with you regarding the CPP here.
