### ISSUE TITLE
cabal-debian-4.23.1 does not compile

### ISSUE THREAD

**Issue by peti** [ddssff/cabal-debian#35]
I'm citing from http://hydra.cryp.to/build/599877/log/raw:

    [11 of 31] Compiling Debian.Debianize.CopyrightDescription ( src/Debian/Debianize/CopyrightDescription.hs, dist/build/Debian/Debianize/CopyrightDescription.o )

    src/Debian/Debianize/CopyrightDescription.hs:40:37:
        Module ‘Debian.Pretty’ does not export ‘display'’

    src/Debian/Debianize/CopyrightDescription.hs:40:47:
        Module ‘Debian.Pretty’ does not export ‘ppDisplay'’

**Comment by ddssff** [comment]
This is due to changes in the debian package.  I'm not sure what to do about this, except to add upper bounds on the dependency versions in the future.

**Comment by peti** [comment]
Personally, I don't care about upper bounds. It's more important to me to get an update that remedies the issue. :-)

**Comment by ddssff** [comment]
Oh, I get it - I forgot to upload to hackage.  Doing that right now!

**Comment by peti** [comment]
Thank you!
