### ISSUE TITLE
Add cabal-debian to stackage

### ISSUE THREAD

**Issue by nomeata** [ddssff/cabal-debian#39]
Hi,

I’d like Debian to follow stackage more closely, as they already identify a consistent set of packages from Hackage. One of our packages missing there is `cabal-debian`. Please consider joining stackage – you’ll get some free QA in return: http://www.stackage.org/authors

Thanks,
Joachim

**Comment by ddssff** [comment]
Sure, I can do this.

**Comment by ddssff** [comment]
I got this far: https://github.com/fpco/stackage/pull/518

**Comment by snoyberg** [comment]
Looks like this can be closed :)
