### ISSUE TITLE
Generated versioned dependencies on libraries provided by GHC

### ISSUE THREAD

**Issue by Kritzefitz** [ddssff/cabal-debian#53]
I was recently packaging Cabal (the library) 1.22.6.0 and cabal-debian generated a bunch of dependencies on libraries that are shipped with GHC.

Normally this wouldn't be a problem without version constraints, but the generated version constraints force the usage of a real package instead of a virtual one, so the dependencies can't actually be satisfied.

I was using cabal-debian 4.31.

**Comment by ddssff** [comment]
Those dependencies should be of the form ghc | lib >= 1.2.3, right?

**Comment by nomeata** [comment]
I observed this as well, but did not yet investigate. My guess is that cabal-debian’s code for figuring out what comes with ghc is broken with ghc-7.10.3 for some reason.

**Comment by ddssff** [comment]
​That is possible, the code is pretty delicate.  I would like to see the output, and have the information required to reproduce it.​

**Comment by Kritzefitz** [comment]
Normally we just omit these dependencies completely.

**Comment by nomeata** [comment]
> Normally we just omit these dependencies completely.

and `cabal-deban` used to do that (maybe only with `--official`?), so the problem is likely the detection.

**Comment by ddssff** [comment]
Ok, I will look at the `--official` behavior.

**Comment by ddssff** [comment]
I'm not seeing this behavior with the current version - 4.32.2.  Could you try this to make sure we are on the same page?

**Comment by Kritzefitz** [comment]
4.32.2 doesn't generate these dependencies. So I think this can be closed.

**Comment by ddssff** [comment]
Thanks!
