### ISSUE TITLE
build-depends for executables not handled correctly

### ISSUE THREAD

**Issue by ddssff** [ddssff/cabal-debian#66]
If a build dependency appears in the library section of a cabal file, both its dev and prof binary deb packages become build dependencies in the debian/control file.  If the dependency appears in an executable section of a cabal file, only its dev binary deb appears in the control file.  Usually the prof package is also required, and should be added.

**Comment by nomeata** [comment]
Hmm, we don't build executables with profiling, so they ought not be required. But maybe this if optimizing the wrong thing (fewer build dependencies) and the logic should be dropped just for the same if simplicity.

**Comment by ddssff** [comment]
I think this may all be cleared up as of 4.38.3.
