### ISSUE TITLE
release 4.38.2 to hackage

### ISSUE THREAD

**Issue by clinty** [ddssff/cabal-debian#67]
Please release a new version that works with modern Cabal to Hackage.

**Comment by ddssff** [comment]
Oops, I just uploaded 4.38.2 but with some local changes - I will go to 4.38.3.

**Comment by ddssff** [comment]
Actually, those local changes look harmless/beneficial.  Let me know if they are ok.   Let me know if they cause any problems and I will fix.

**Comment by ddssff** [comment]
Oh, it didn't upload.   Fixing that.

**Comment by ddssff** [comment]
do you want hackage maintainer permissions?

**Comment by ddssff** [comment]
Oh, I uploaded this a few days ago.  Let me know whether it does what you need.
