### ISSUE TITLE
The copyright should be machine-readable

### ISSUE THREAD

**Issue by nomeata** [ddssff/cabal-debian#7]
The template is
```
Format: http://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: foo
Upstream-Contact: Jack Upstream Developer <upstream@example.com>
Source: http://hackage.haskell.org/package/foo

Files: *
Copyright: 1970 Jack Upstream Developer
License: foo license

Files: debian/*
Copyright: held by the contributors mentioned in debian/changelog
License: foo license

License: foo license
 This is the text of the foo license.
```
Where “This is the text of the foo license.“ is replaced by the upstream license. Bonus points for extracting the copyright from that file and putting it in here separately.

(This whole copyright file handling probably needs more finetuning.)

**Comment by ddssff** [comment]
This should be closed by 9b08957461913035b39f3f5778ac811ef47e923e.

**Comment by ddssff** [comment]
But I'd better verify...

**Comment by ddssff** [comment]
Ok, this is ready for testing.
